apiVersion: v1 # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
kind: Service
metadata:
  name: personsimulator-${APP_VERSION_UNDERSCORE}-svc
  labels:
    app: personsimulator-${APP_VERSION_UNDERSCORE}-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    name: personsimulator-${APP_VERSION_UNDERSCORE}web
  selector:
    app: personsimulator-${APP_VERSION_UNDERSCORE}-svc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: personsimulator-${APP_VERSION_UNDERSCORE}-sfs
spec:
  serviceName: "personsimulator-${APP_VERSION_UNDERSCORE}-svc"
  replicas: 6
  selector:
    matchLabels:
      app: personsimulator-${APP_VERSION_UNDERSCORE}-sfs
  template:
    metadata:
      labels:
        app: personsimulator-${APP_VERSION_UNDERSCORE}-sfs
    spec:
      containers:
      # pod machine name must be less 15 - 2 because a '-x' will be appended
      - name: psim-${APP_VERSION_UNDERSCORE}
        image: fredcontainerregistry.azurecr.io/donation.personsimulator.console:${APP_VERSION}
        ports:
        - containerPort: 8080
          name: psim-${APP_VERSION_UNDERSCORE}
        env: # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
        - name: donationEndPointIP
          value: "${APP_ENDPOINT_IP}"
        - name: donationEndPointPort
          value: "${APP_ENDPOINT_PORT}"
      imagePullSecrets:
      - name: fredcontainerregistry
