apiVersion: v1 # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
kind: Service
metadata:
  name: queueprocessor-${APP_VERSION_UNDERSCORE}kuard
  labels:
    app: queueprocessor-${APP_VERSION_UNDERSCORE}kuard
spec:
  type: NodePort
  ports:
  - port: 8080
    name: queueprocessor-${APP_VERSION_UNDERSCORE}web
  selector:
    app: queueprocessor-${APP_VERSION_UNDERSCORE}kuard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queueprocessor-${APP_VERSION_UNDERSCORE}kuard
spec:
  serviceName: "queueprocessor-${APP_VERSION_UNDERSCORE}kuard"
  replicas: 1
  selector:
    matchLabels:
      app: queueprocessor-${APP_VERSION_UNDERSCORE}kuard
  template:
    metadata:
      labels:
        app: queueprocessor-${APP_VERSION_UNDERSCORE}kuard
    spec:
      containers:
      # pod machine name must be less 15 - 2 because a '-x' will be appended
      - name: qpro-${APP_VERSION_UNDERSCORE}
        image: fredcontainerregistry.azurecr.io/donation.queueprocessor.console:${APP_VERSION}
        ports:
        - containerPort: 8080
          name: qpro-${APP_VERSION_UNDERSCORE} # was queueprocessor-${APP_VERSION_UNDERSCORE}web
      imagePullSecrets:
      - name: fredcontainerregistry
