apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fdotnetcorewebapp-deployment-1.0.3
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fdotnetcorewebapp
        version: 1.0.3
    spec:
      containers:
      - name: fdotnetcorewebapp-pod
        image: fredcontainerregistry.azurecr.io/fdotnetcorewebapp:1.0.3
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: fredcontainerregistry
